* Modificación del título del TFG
** Identificación

Ares Aguilar Sotos, con DNI 48150218V y correo electrónico ares.aguilar@estudiante.uam.es, estudiante de Grado en la Escuela Politécnica Superior de la Universidad Autónoma de Madrid.

** Expone

Que, para el Doble Grado en Ingeniería informática y Matemáticas, tiene registrado y asignado con fecha de Octubre de 2015 el Trabajo de Fin de Grado con código 1516_049_COIS y nombre "Modelado del comportamiento de la igualdad de genero en los países con IA".

Que el día 7 de Noviembre del 2016 entregó la Solicitud de Modificación de Trabajo Fin de Grado con número 201600026681, y que desde administración se solicitó, por correo electrónico, un escrito alegando las razones del cambio porque "no es un cambio elemental sino en apariencia bastante distinto al del trabajo inicialmente asignado".

Que el título nuevo propuesto, "Predicción y análisis de series temporales de la evolución de los derechos LGBT en el mundo a través de técnicas de aprendizaje automático", no supone un trabajo distinto al inicialmente asignado, sino que es un cambio elemental, por los siguientes

** Motivos

   1. La frase "Modelado del comportamiento" del título original tiene el mismo significado, en este contexto, que "Predicción y análisis". No obstante, si el lector no lo entiende así, ruego me lo haga saber ya que no supondría problema alguno cambiar esta parte.

   2. La frase "de series temporales (...) a través de técnicas de aprendizaje automático" del nuevo título supone simplemente una concreción de la frase en el título original "con IA", ya que el aprendizaje automático es una rama dentro de la inteligencia artificial. Adicionalmente, se concreta que el tipo de datos empleados son series temporales.

   3. La frase "de la evolución de los derechos LGBT en el mundo" difiere de la original, "de la igualdad de género", únicamente en el tipo de datos que se emplearan. La base de datos tiene iguales características y los objetivos técnicos y analíticos del trabajo permanecen intactos. Simplemente se corrige que la base de datos de series temporales empleada no será de igualdad de género sino de igualdad en derechos LGBT, por otra parte, altamente relacionadas.

** Solicita

Que, dado que la única modificación en dicho trabajo es la serie temporal empleada, siendo las técnicas empleadas como los objetivos perseguidos los mismos, se modifique el título a "Predicción y análisis de series temporales de la evolución de los derechos LGBT en el mundo a través de técnicas de aprendizaje automático".
